export const FETCH_POSTS = 'FETCH_POSTS';
export const TOGGLE_LOCATION_POPUP = 'TOGGLE_LOCATION_POPUP';
export const SAVE_ITEM = 'SAVE_ITEM';
export const TOGGLE_MIC_POPUP = 'TOGGLE_MIC_POPUP';
export const TOGGLE_KEYBOARD_POPUP = 'TOGGLE_KEYBOARD_POPUP';

// REQUEST | SUCCESS | FAILURE

export const LOGIN_SUCESS = 'LOGIN_SUCESS';
export const USER_UNLOGIN = 'USER_UNLOGIN';

export const USER_INFO_REQUEST = 'USER_INFO_REQUEST';
export const USER_INFO_SUCESS = 'USER_INFO_SUCESS';
export const USER_INFO_FAILURE = 'USER_INFO_FAILURE';

